// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/google/wire"
	"psaraiva/d3/internal/entity"
	"psaraiva/d3/internal/event"
	"psaraiva/d3/internal/infra/database"
	"psaraiva/d3/internal/infra/web"
	"psaraiva/d3/internal/usecase"
	"psaraiva/d3/pkg/events"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func NewCreateOrderUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.CreateOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	createOrderUseCase := usecase.NewCreateOrderUseCase(orderRepository, orderCreated, eventDispatcher)
	return createOrderUseCase
}

func NewUpdateOrderUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.UpdateOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	orderUpdated := event.NewOrderUpdated()
	updateOrderUseCase := usecase.NewUpdateOrderUseCase(orderRepository, orderUpdated, eventDispatcher)
	return updateOrderUseCase
}

func NewWebOrderHandler(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *web.WebOrderHandler {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	orderUpdated := event.NewOrderUpdated()
	orderEvents := &event.OrderEvents{
		OrderCreated: orderCreated,
		OrderUpdated: orderUpdated,
	}
	webOrderHandler := web.NewWebOrderHandler(eventDispatcher, orderRepository, orderEvents)
	return webOrderHandler
}

// wire.go:

var setOrderRepositoryDependency = wire.NewSet(database.NewOrderRepository, wire.Bind(new(entity.OrderRepositoryInterface), new(*database.OrderRepository)))

var setEventDispatcherDependency = wire.NewSet(events.NewEventDispatcher, event.NewOrderCreated, event.NewOrderUpdated, wire.Bind(new(events.EventDispatcherInterface), new(*events.EventDispatcher)), wire.Bind(new(events.EventInterface), new(*event.OrderCreated)), wire.Bind(new(events.EventInterface), new(*event.OrderUpdated)))

var setOrderCreatedEvent = wire.NewSet(event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)))

var setOrderUpdatedEvent = wire.NewSet(event.NewOrderUpdated, wire.Bind(new(events.EventInterface), new(*event.OrderUpdated)))

var setOrderEvents = wire.NewSet(event.NewOrderCreated, event.NewOrderUpdated, wire.Struct(new(event.OrderEvents), "OrderCreated", "OrderUpdated"))
