services:
  d3-mysql:
    image: mysql:8.0
    container_name: d3-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./init-scripts/mysql:/docker-entrypoint-initdb.d

  d3-rabbitmq:
    image: rabbitmq:3-management
    container_name: d3-rabbitmq
    environment:
      RABBITMQ_USER: "guest"
      RABBITMQ_PASS: "guest"
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  mysql:
    driver: local
