services:
  d3-mysql:
    image: mysql:8.0
    container_name: d3-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./init-scripts/mysql:/docker-entrypoint-initdb.d
    networks:
      - d3-network

  d3-rabbitmq:
    image: rabbitmq:3-management
    container_name: d3-rabbitmq
    environment:
      RABBITMQ_USER: "guest"
      RABBITMQ_PASS: "guest"
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - d3-network

  d3-go:
    build:
      context: ./
      dockerfile: ./docker/go/Dockerfile
    container_name: d3-go
    restart: always
    ports:
      - 7000:8000
      - 7080:8080
      - 40051:50051
    depends_on:
      - d3-mysql
      - d3-rabbitmq
    networks:
      - d3-network

volumes:
  mysql:
    driver: local

networks:
  d3-network:
    driver: bridge